name: Deploy state s3 and Dynamodb table

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.9

      - name: Terraform init,plan and apply
        working-directory: ./BASIC-INFRA-SMALL-SCALE/state-s3
        run: | 
          terraform init
          terraform plan
          terraform apply -auto-approve

      - name: Commit statefile
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Updated statefile"
          branch: master
          repository: ./BASIC-INFRA-SMALL-SCALE/state-s3
          file_pattern: 'terraform.tfstate*'
          commit_user_name: stavtnameh
          commit_user_email: hemanth.v@beehyv.com